name: Hourly Bot Restart & CI/CD

on:
  # ඔබ කෝඩ් එක වෙනස් කර push කරන විට මෙය දියත් වේ (සාමාන්‍ය භාවිතය)
  push:
    branches: [ "main" ]
  
  # සෑම පැයකටම වරක් (මිනිත්තුව 0 ට) මෙය ස්වයංක්‍රීයව දියත් වේ
  schedule:
    # '0 * * * *' යනු සෑම පැයකම ආරම්භය (e.g., 10:00, 11:00, 12:00 UTC)
    - cron: '0 * * * *' 

  # ඔබට අවශ්‍ය ඕනෑම වේලාවක මෙය Manual-Run කිරීමට පහසුකම් සලසයි
  workflow_dispatch: 

jobs:
  build:
    # මෙය Heroku හෝ වෙනත් VPS සේවාවක් මත නම්, Heroku Deployment Action එකක් මෙතනට ඇතුළත් කළ හැක.
    # සරලම ක්‍රමවේදය පහත දැක්වේ.
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v3

      - name: 2. Set up Node.js (v20)
        uses: actions/setup-node@v3
        with:
          node-version: 20.x 
          cache: 'npm'
          
      - name: 3. Install dependencies
        # අවශ්‍ය Node modules ස්ථාපනය කරයි.
        run: npm install

      - name: 4. Start or Deploy Application
        # මෙම command එක මඟින් බොට් process එක නැවත ආරම්භ වේ.
        run: npm start

￼Enter
